version: '2.2'

services:

  consumer:
    build: consumer
    networks: 
    - rabbitNetwork

  producer:
    build: producer
    networks: 
    - rabbitNetwork

  database:
    image: mongo
    networks:
    - rabbitNetwork
    ports:
    - 27017:27017

  rabbitmq:
    image: rabbitmq:latest
    networks: 
    - rabbitNetwork
    ports:
    - 5672:5672
    - 15672:15672

networks:
  rabbitNetwork:
